### ISSUE TITLE
The repository 'http://deb.wakemeops.com/wakemeops stable InRelease' is not signed

### ISSUE THREAD

**Issue by braykov** [upciti/wakemeops#1804] opened 2023-10-24 19:49 UTC
### Describe the Bug

Just created a docker file with the exact contents of the example in the Readme.

### Steps to Reproduce

1. Got to this project's main page
2. Copy the contents of the example Dockerfile
3. Create a Dockerfile, paste and build it

### Expected Behaviour

We should end up with a properly built image

### Actual Behaviour

```

[+] Building 22.9s (5/5) FINISHED                                                            docker:desktop-linux
 => [internal] load .dockerignore                                                                            0.0s
 => => transferring context: 62B                                                                             0.0s
 => [internal] load build definition from Dockerfile-wmo                                                     0.0s
 => => transferring dockerfile: 167B                                                                         0.0s
 => [internal] load metadata for docker.io/wakemeops/debian:bullseye                                         0.0s
 => CACHED [1/2] FROM docker.io/wakemeops/debian:bullseye                                                    0.0s
 => ERROR [2/2] RUN install_packages     helm=3.7.2*     kustomize=4.4.1*     kubectl=1.23.1*               22.9s
------
 > [2/2] RUN install_packages     helm=3.7.2*     kustomize=4.4.1*     kubectl=1.23.1*:
10.10 E: Failed to fetch http://deb.wakemeops.com/wakemeops/dists/stable/InRelease  403  CoachingSession(viaCookie) [IP: 78.47.250.38 80]
10.10 E: The repository 'http://deb.wakemeops.com/wakemeops stable InRelease' is not signed.
10.11 apt failed, retrying
16.46 E: Failed to fetch http://deb.wakemeops.com/wakemeops/dists/stable/InRelease  403  CoachingSession(viaCookie) [IP: 78.47.250.38 80]
16.46 E: The repository 'http://deb.wakemeops.com/wakemeops stable InRelease' is not signed.
16.46 apt failed, retrying
22.88 E: Failed to fetch http://deb.wakemeops.com/wakemeops/dists/stable/InRelease  403  CoachingSession(viaCookie) [IP: 78.47.250.38 80]
22.88 E: The repository 'http://deb.wakemeops.com/wakemeops stable InRelease' is not signed.
------
Dockerfile-wmo:3
--------------------
   2 |
   3 | >>> RUN install_packages \
   4 | >>>     helm=3.7.2* \
   5 | >>>     kustomize=4.4.1* \
   6 | >>>     kubectl=1.23.1*
   7 |
--------------------
ERROR: failed to solve: process "/bin/sh -c install_packages     helm=3.7.2*     kustomize=4.4.1*     kubectl=1.23.1*" did not complete successfully: exit code: 100
```

### Environment

```shell
uname -a && cat /etc/*release
Darwin M-NMXPWYJN5H 22.6.0 Darwin Kernel Version 22.6.0: Fri Sep 15 13:41:28 PDT 2023; root:xnu-8796.141.3.700.8~1/RELEASE_ARM64_T6000 arm64 arm Darwin
zsh: no matches found: /etc/*release
```

**Comment by fyhertz** [comment] 2023-11-03 16:27
Mmm I cannot reproduce the error, can you retry? Maybe it was a transient error.

Closing for now.

**Closed by fyhertz** 2023-11-03 16:27 UTC
Labels: bug

**Comment by braykov** [comment] 2023-11-09 10:26
You are right, that turned out to be a firewall issue.
